In [77]:
import pandas as pd
df = pd.read_csv('ds_salaries.csv')
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

In [78]:
# 1. El promedio general de los salarios, desviación estándar, quintiles y rango.
# (hint: escoge la columna adecuada para comparar)

media = df['salary'].mean()
desviacion_estandar = df['salary'].std()
q1 = df['salary'].quantile(0.2)
q5 = df['salary'].quantile(0.8)
minimo = df['salary'].min()
maximo = df['salary'].max()
rango = maximo-minimo

print(f'media: {round(media,4)} \n desviacion_estandar: {round(desviacion_estandar,4)}')
print(f'qintil 1: {round(q1,4)} \n quintil 5: {round(q5,4)}\n rango: {round(rango,4)}')

media: 190695.5718
 desviacion_estandar: 671676.5005
qintil 1: 85000.0
 quintil 5: 191475.0
 rango: 30394000

In [79]:
# 2. Una comparación entre los salarios agrupados por 3 diferentes categorías a 
# tu elección. ¿Para cuál de ellas las medidas de tendencia central son más
# representativas? ¿Para cuál son menos representativas? Explica.

# primera forma
media_salario_por_employment_type = df.groupby('employment_type')['salary'].mean()
media_salario_por_company_size = df.groupby('company_size')['salary'].mean()
media_salario_por_experience_level = df.groupby('experience_level')['salary'].mean()
print(round(media_salario_por_employment_type,2),'\n')
print(round(media_salario_por_company_size,2),'\n')
print(round(media_salario_por_experience_level,2))

# Grupo1: El promedio de salarios de los empleados por su tipo de empleo 'trabajo freelance' (FL) es superior 
# comparado con las demás categorías 'tiempo completo' (FT), por 'contrato' (CT) 
# y 'tiempo parcial' (PT) que es signicativamente inferior.

# Grupo2: El promedio de salarios de los empleados por el tamaño de la compañia es significativamente más alto en una empresa grande 
# y con más de 250 empleados (L) que en las demás agrupaciones, además cabe mencionar que los salarios en una empresa mediana
# con 50 a 250 empleados (M) es bajo comparandolo con una empresa pequeña com menos de 50 empleados (S) 
# donde el salario medio es casi el doble.

# Grupo3: Finalmente, el promedio del salario por el nivel de experiencia presenta un ligero empate entre los salarios recibidos
# por empleados con nivel medio (MI) y los recibidos por empleado con un nivel ejecutivo / director (EX), mientras que los salarios medios 
# de los empleados del nivel senior / experto (SE) ganan ligeramente menos que los de nivel de entrada / junior (EN).

# la medida de tendencia central, promedio, es más representativa para los salarios por tamaño de compañia, pues refleja 
# las caracteristicas del grupo más grande, esto nos permite hacer inferencias confiables sobre toda la población.
# En contraparte la menos representativa es la agrupación por nivel de experiencia, pues se requiere más información que solo el
# promedio para afirmar que los salarios medios de los empleados del nivel senior / experto (SE) sean ligeramente menores 
# que los de nivel de entrada / junior (EN).

employment_type
CT    113300.00
FL    288755.50
FT    191146.54
PT     79910.82
Name: salary, dtype: float64

company_size
L    438794.37
M    150712.84
S    281430.10
Name: salary, dtype: float64

experience_level
EN    188381.18
EX    246802.20
MI    248200.31
SE    170048.97
Name: salary, dtype: float64

In [50]:
# segunda forma
tabla_pivote = pd.pivot_table(df,
                              #columns = ,
                              index = ['employment_type','company_size','experience_level'],
                              values= 'salary',
                              aggfunc= 'mean')    
round(tabla_pivote,2)

                                                   salary
employment_type company_size experience_level
CT              L            EN                 100000.00
                             MI                 270000.00
                M            EN                  29000.00
                             MI                   7500.00
                             SE                  97500.00
                S            EX                 416000.00
                             MI                  38500.00
FL              L            MI                  20000.00
                M            EN                 100000.00
                             MI                  52518.33
                             SE                  50000.00
                S            EN                  50000.00
                             MI                2400000.00
                             SE                  55000.00
FT              L            EN                 202875.16
                             EX                 623846.15
                             MI                 757307.50
                             SE                 350949.42
                M            EN                 180911.40
                             EX                 198110.01
                             MI                 124834.02
                             SE                 153981.07
                S            EN                 238808.86
                             EX                 157800.00
                             MI                 455955.63
                             SE                 155670.73
PT              L            EN                  58500.00
                             MI                  54500.00
                M            EN                  57690.00
                             MI                 400000.00
                S            EN                  64120.67

In [81]:
# 3. ¿Qué cargos reciben mejores sueldos en las empresas con sede en Estados Unidos?
# cargos: job_title
# sueldos: salary y salary_in_usd
# usa: company_location

TablaPivote2 = pd.pivot_table(df[df['company_location']=='US'],
                             index = 'job_title',
                             values = 'salary',
                             aggfunc = 'max')
TablaPivote3 = TablaPivote2.sort_values(by='salary', ascending=False)
TablaPivote3 = TablaPivote3.reset_index()
TablaPivote3.head(10)

                            job_title    salary
0                     BI Data Analyst  11000000
1                Data Science Manager   4000000
2                      Data Scientist   2500000
3                  Research Scientist    450000
4  Applied Machine Learning Scientist    423000
5            Principal Data Scientist    416000
6                 Data Analytics Lead    405000
7                        Data Analyst    385000
8              Applied Data Scientist    380000
9                      Data Architect    376080